/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */
/* REMEMBER TO REMOVE THE PACKAGE LINE BEFORE SUBMISSION */
    package PLMParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"Hello World\"",
  };

}
